author: 'escapace'
description: 'Sets up HashiCorp Vault in your GitHub Actions workflow.'
name: 'Setup HashiCorp Vault'

branding:
  color: 'purple'
  icon: 'terminal'

runs:
  main: 'lib/action/lib/node/index.js'
  using: 'node24'

inputs:
  vault-version:
    default: 'latest'
    description: 'The version of Vault to install. Instead of full version string you can also specify a semantic version range (for example `^1.10.4`) to install the latest version satisfying the constraint. A value of `latest` will install the latest version of Vault. Defaults to `latest`.'
    required: false
