name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    permissions:
      checks: read
      contents: read
      pull-requests: read
      statuses: read
    uses: escapace/workflows/.github/workflows/context.yaml@trunk

  typescript-checks:
    needs:
      - context
    permissions:
      contents: read
      packages: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: escapace/workflows/.github/workflows/ci-typescript.yaml@trunk
    with:
      enable-codecov: ${{ !github.event.repository.private }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
      version: ${{ needs.context.outputs.version }}

  action-smoke-test:
    needs:
      - context
      - typescript-checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        enterprise: [false, true]
        os: [ubuntu-latest]
        version:
          - ^1.21.0
          - latest
    steps:
      - name: checkout
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ needs.context.outputs.ref }}
      - name: setup
        uses: ./
        with:
          enterprise: ${{ matrix.enterprise }}
          vault-version: ${{ matrix.version }}
      - name: check version
        run: vault --version

  continuous-integration:
    if: ${{ always() }}
    needs:
      - context
      - typescript-checks
      - action-smoke-test
    runs-on: ubuntu-latest
    steps:
      - name: fail if any required job did not succeed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: exit 1
      - name: pass if all required jobs succeeded
        if: ${{ !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped')) }}
        run: exit 0
